### PR TITLE
Fix format action

### PR DESCRIPTION
**Pull request by ankith26**
Fixes the glob pattern to match all python files

### CODE REVIEW

**Comment by ankith26** [comment]
sorry, this PR was accidentally opened on the wrong repo :sweat_smile:

**Comment by Groverkss** [comment]
Not sure why you felt the need to fork this :) Is there something preventing you from directly contributing to this repository?

**Comment by ankith26** [comment]
Well, we decided to fork the repo because we assumed the authors of this repo either graduated or are in the process of it and hence would not have the time or need to continue to maintain this project.

That being said, if our assumption is wrong and you are still interested in maintaining this project we would love to work with you :smile:

**Comment by Groverkss** [comment]
> Well, we decided to fork the repo because we assumed the authors of this repo either graduated or are in the process of it and hence would not have the time or need to continue to maintain this project.
> 
> That being said, if our assumption is wrong and you are still interested in maintaining this project we would love to work with you 😄

@necessary129 Is still in university. Also, I don't think reviewing code takes a few minutes of my time, so you are free to send PRs to this repo.

Generally, I really don't think this project needs any work. It's a small self-contained project and it does what it does really well. I would be curious what changes you have for this project which are not bloat.

**Comment by ankith26** [comment]
We have expansion plans for this project, which may be diverging from your original plans. Due to this, forking seemed like the best way forward as it preserves your original work here, and our works that we have built on top of yours also gets its own space.

**Pull request closed without merging**
