### PR TITLE
Added The Dance Crew in bot/server_config.ini

### PR DESCRIPTION
**Pull request by sriramdvt**

### CODE REVIEW

**Comment by GaurangTandon** [comment]
@sriramdvt We have restarted the bot! You can add the bot to your server now :)

**Comment by sriramdvt** [comment]
@GaurangTandon Thank you! I'm unable to see the bot in the server though. After authorizing the bot to join the server, I'm stuck on "Read the instructions to invite the bot here here: https://github.com/Groverkss/Discord-CAS/blob/master/README.md"

**Comment by Groverkss** [comment]
Try now again. @GaurangTandon forgot to pull your commits xD.

**Comment by sriramdvt** [comment]
Haha yup the bot's in the server now, thank you so much! :D

**Pull request merged**
